### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by offizium-berndstorath** [unjs/destr#123]
### Environment

any

### Reproduction

none

### Describe the bug

Its marketed as sometimes slower but most times faster than JSON.parse. But it is just a wrapper around JSON.parse with better types and quick checks before

**Comment by pi0** [comment]
You can check the [benchmarks](https://github.com/unjs/destr/blob/main/BENCH.md) or run them locally (check for `faster than JSON.parse` results).

**Comment by pi0** [comment]
I have mentioned "arbitrary inputs" not Valid JSON and **clearly** saying destr is SLOWER than JSON.parse for security checks reason, i don't know how it can be a lie but i let you to be the judge.

**Comment by pi0** [comment]
As I said before, your context of what is common is not the same as the one this library is made for (or even named after! it is "destr" not "dejson"). "artibrary input" is not the same as "json input", it means any string input (like values from a KV store) and it is all clearly written in the readme, (obviously not for marketing but for transparency, if you read it right)
