### ISSUE TITLE
Tiny typo in the GitHub project description -> artibrary vs arbitrary

### ISSUE THREAD

**Issue by pano9000** [unjs/destr#125]
### Describe the change

The "About" section on the right side of the GitHub page currently contains a tiny typo.

Instead of "**arbitrary** inputs" it currently says "**artibrary** inputs".
:-)

### URLs

https://github.com/unjs/destr

### Additional information

- [X] Would you be willing to help?

**Comment by pi0** [comment]
thnx ❤️
