### ISSUE TITLE
Type verification and enforcement

### ISSUE THREAD

**Issue by husayt** [unjs/destr#127]
### Describe the feature

While `destr` is typesafe, there is no guarantee that field types would be as they are specified. For instance for `{age:number}` it still could return `{age: "7" }`, whereas  `{age: 7 }` would be expected. Need some kind of verification logic, to guarantee types are as expected. Maybe a good idea to use a [type guard](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I think a validator layer like zod/valibot would perhaps be better idea if "runtime" type safety is desired. This feels out of scope of destr. (both solutions can be combined)

**Comment by husayt** [comment]
Thank You Pooya

**Comment by jcuenod** [comment]
Without this feature, I think it's a bit disingenuous to say this library can be used for "Type Safety". If I'm understanding correctly, these are equivalent and the latter does not improve type safety:

```
const obj = destr<MyInterface>("{}")
const obj = destr("{}") as MyInterface
```
