### ISSUE TITLE
Support the reviver option of JSON.parse

### ISSUE THREAD

**Issue by cjpearson** [unjs/destr#131]
### Describe the feature

It would be helpful if users of `destr` could provide a reviver function which is passed through to `JSON.parse`. `destr` already uses this parameter for `jsonParseTransform`, but I think it should be possible to chain the user's reviver function.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Can you please share examples that this might be useful?

**Comment by cjpearson** [comment]
I'd noticed unstorage will serialize a `Buffer` on `setItem`. I was thinking an approach like [this](https://stackoverflow.com/a/34557997/754604) might be useful for deserializing.

**Comment by pi0** [comment]
hmm I don't think unstorage for raw operations should even do json serialization/desrialization. It uses a specific [signature](https://github.com/unjs/unstorage/blob/6163be0eb5035b54f3a576086e7b41a48efa3607/src/_utils.ts#L71) (in text-only drivers).

Do you have any other usecase in mind? (if not, I prefer to keep destr simple -- simplicity matters most..)

**Comment by cjpearson** [comment]
The serialization seems to happen here: https://github.com/unjs/unstorage/blob/6163be0eb5035b54f3a576086e7b41a48efa3607/src/_utils.ts#L43

To me this is not a high priority. I filed the issue since I thought it might make sense to match the `JSON.parse` API, but I understand the motivation to keep things limited as well.

**Comment by cjpearson** [comment]
Sounds good! Working on using `setItemRaw` for the cache is actually how I ended up here :D

**Comment by pi0** [comment]
Yep, we need to migrate but needs lots of risky changes which makes only possible way to create a new rewrite for nitro. (I will involve you as soon as got into motion)
