### ISSUE TITLE
Loading json with blobs take a long time

### ISSUE THREAD

**Issue by jaroel** [unjs/destr#132]
### Environment

bun on macos

### Reproduction

Store a json with some bas64 encoded image (a few 100 kbs will do). Load them.

### Describe the bug

I use unstorage to persist large json blobs (incl images) to disk. Loading them takes a long long long time.
There's some regexps that validate content on load, that might be something.

**Comment by pi0** [comment]
JSON parsing normally has overhead. In the context of unstorage I have two advices:

- If the driver you are using supports `setItemRaw` natively using it skips serialization all alltogether
- If you are storing an object (blob), first convert it manually using `JSON.stringify()` and pass to `setItem` (ie to minimize perf overhead)

destr cannot do anything faster than what userland runtime (Node.js, etc) allows. This is not a bug with this library.
