### ISSUE TITLE
Warning when dropping keys for saftey in dev mode

### ISSUE THREAD

**Issue by manniL** [unjs/destr#25]
### Describe the feature

Hey! Based on https://github.com/nuxt/nuxt.js/issues/15736, we could give out warnings in `dev` mode when keys are dropped (`constructor`/`__proto__`).

Would that make sense?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We could do this only by using conditional exports (since destr cannot depend on `process.env`) and if people not use proper export conditions, they will get warning also in production.

I'm fine with trying to always show a warning when detecting potential issues if too verbse can revert.
