### ISSUE TITLE
destr does not unescape special chars if json contains only string

### ISSUE THREAD

**Issue by eungkyu** [unjs/destr#89]
### Environment

destr 2.0.1
Node.js 18

### Reproduction

```
JSON.parse('"a\\nb"') == destr('"a\\nb"')
```
should be true

### Describe the bug

https://github.com/unjs/destr/blob/769122d27f659bdbd635055e7564426de76bba01/src/index.ts#L40

At this line, destr returns string just stripped double quote.

**Comment by pi0** [comment]
Thanks for report. Will be fixed in next release.
