### ISSUE TITLE
Memory leak in `destr` package, Nuxt 3 production usage

### ISSUE THREAD

**Issue by mrauhu** [unjs/destr#9]
Hello, @pi0.

I found a memory leak, that affects Nuxt 3 framework, because the `destr` package is used as default [`parseResponse` option](https://github.com/unjs/ohmyfetch/blob/96a9cbc847b7df3e30b6634e0f71c04dfdb14424/src/fetch.ts#L142) in the `ohmyfetch`, that used in the Nuxt 3 [`useFetch()` function as `$fetch`](https://github.com/nuxt/framework/blob/46c656c4b85c3622b99a7c4f6a01f5b11c830be6/packages/nuxt/src/app/composables/fetch.ts#L55).

### Flamegraph

![image](https://user-images.githubusercontent.com/2821574/176434478-af02b934-2e12-4715-97c6-e03a62e60ed2.png)

### Table

![image](https://user-images.githubusercontent.com/2821574/176434879-eba136ed-df84-420d-83a8-1c930506f8a6.png)

### Memory usage

![image](https://user-images.githubusercontent.com/2821574/176466004-88cf6d52-b98c-4904-b535-6fe1eb1e75bb.png)

## Temporary fix for Nuxt 3

1. Create a local TypeScript file (`lib/use-fetch.ts`) with copy of [`useFetch()`](https://github.com/nuxt/framework/blob/46c656c4b85c3622b99a7c4f6a01f5b11c830be6/packages/nuxt/src/app/composables/fetch.ts) function.

2. Add custom `parseResponse()` function:

    ```ts
    import type { FetchOptions } from 'ohmyfetch';
    
    /**
     * Parse response
     * @description Replace of `destr()` function to prevent memory leak
     * @param responseText
     */
    const parseResponse: FetchOptions['parseResponse'] = (responseText) => {
      // Send empty string if zero length
      if (responseText.length === 0) {
        return '';
      }
    
      try {
        return JSON.parse(responseText);
      } catch (_e) {
        return responseText;
      }
    };
    ```

2. Replace `_fetchOptions` constant in the copy of [`useFetch()`](https://github.com/nuxt/framework/blob/46c656c4b85c3622b99a7c4f6a01f5b11c830be6/packages/nuxt/src/app/composables/fetch.ts#L41-L44) function:
  
    ```ts
      const _fetchOptions = {
        ...opts,
        parseResponse,
        cache: typeof opts.cache === 'boolean' ? undefined : opts.cache
      }
    ```

3. Use patched `useFetch()` function instead of build-in.

Because, right now there is no way to provide custom `parseResponse()` function as option of the `useFetch()` without error.

Best wishes,
Sergey.

**Comment by pi0** [comment]
Hi @mrauhu thanks for making the issue and providing a workaround but are you sure the memory leak originates from destr? Can you please provide a minimal reproduction? 🙏🏼

**Comment by pi0** [comment]
Any update on this?

**Comment by mrauhu** [comment]
> Any update on this?

@pi0 unfortunately, I can't create a reproduction in the isolated environment only for `destr` package.

Changes after replacing `destr()` to `JSON.parse()` function for the production server, a week of observations:

| `$fetch` `parseResponse` option | Max memory usage, MB |
|---------------------------------|:--------------------:|
| `destr()`                       |                  509 |
| `JSON.parse()`                  |                  112 |

## Memory usage

![image](https://user-images.githubusercontent.com/2821574/177640226-a487fd53-e472-4e2c-ab73-9609693af48e.png)

### Flamegraph

![image](https://user-images.githubusercontent.com/2821574/177638693-a8bcbbe3-d10f-4133-b5fb-eb20b2b97b33.png)

### Table

![image](https://user-images.githubusercontent.com/2821574/177639102-c0e2469b-e065-4be1-b976-4182d6f03dd8.png)

**Comment by pi0** [comment]
Higher memory usage is likely the overhead of regex checkers over a heavy payload. What happens after max memory usage? Do you auto restart? Also what is prod Node.js version?

**Comment by mrauhu** [comment]
> Higher memory usage is likely the overhead of regex checkers over a heavy payload. 

API responses is nested tree JSON documents, 50—100 KB size.

> What happens after max memory usage?

Restart of container.

> Do you auto restart?

Yes.

> Also what is prod Node.js version?

Node.js 16.14.2, a Docker image based on the https://github.com/astefanutti/scratch-node.

**Comment by dargmuesli** [comment]
@mrauhu with which application did you examine the memory leak with?

**Comment by mrauhu** [comment]
@dargmuesli it's part of the Datadog APM.

The [`dd-trace-js`](https://github.com/DataDog/dd-trace-js) package was used for tracing. Under the hood it's using the [`@datadog/pprof`](https://github.com/DataDog/pprof-nodejs) package, fork of [`pprof`](https://github.com/google/pprof-nodejs).

The [Datadog Contentious Profiler](https://docs.datadoghq.com/tracing/profiler/) used for visualization.

**Comment by mcstover** [comment]
@mrauhu Might I ask how you implemented the dd-trace-js in your application? Did you use a module or a server plugin? Thanks!

**Comment by pi0** [comment]
Hi. Kindly this issue still needs a minimal reproduction. Please ping to reopen if you still believe there is a possible memory leak in destr itself.
