### ISSUE TITLE
Alternative to JSON.stringify

### ISSUE THREAD

**Issue by angelhdzmultimedia** [unjs/destr#95]
### Describe the feature

Was searching all over unjs repo and Google to find the JSON.stringify equivalent of destr and didn't find anything.

If there's one please provide the name, otherwise take it as a feature request. :) 

High appreciation to the unjs ecosystem. 🔥💚👏

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for kind words and feature request. What specifically are you looking for serializer that differs `JSON.stringify`?

**Comment by angelhdzmultimedia** [comment]
> Thanks for kind words and feature request. What specifically are you looking for serializer that differs `JSON.stringify`?

Don't know! Feels odd using destr for JSON.parse and not having an unjs alternative for JSON.stringify...
I'm passionate of consistency hehe. 😆

Also room for improving JSON.stringify's perf? 

### Motivation
I'm exploring all unjs tools because I'm building an UI for Nuxt and NestJS scaffolding, like `nuxi add` and `nuxi new`, or `nest generate` and `nest new`, but with a graphical UI. You select the root path for all apps (projects), select the type (nuxt or nestjs for now), and then you create the apps, and select them, and then you can add templates to them. Like Nuxt devtools, but more specific for my needs. The pinia stores are created like   stores/store/index.ts, stores/store/actions.ts, stores/store/state.ts, you can select the global flag of middleware, the HTTP method of server API routes and path parameter, etc.

### Final Words
If there's not alternative, or no plans to make one, just close the Issue kindly. It was more of a curiosity. Wanted to leave this in a Discussions, but it's not available.

Have a nice rest of the day.

**Comment by pi0** [comment]
No worries nice about your UI idea (FYI, you can also use nuxi programmatic API for this and we also plan to support more template utils thet are to be reused for vscode extension and possibly devtoils so i guess also a good match for your project idea at least for Nuxt. Feel free to drop an issue in nuxi or dm me in discord if wanted to do it!)

——

Regarding this, we could expose serialize method that is essentially alias of JSON.serialize but allow me think more if there is something other than same alias that adds value to introduce…
